<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\Galeria;

/**
 * GaleriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GaleriaRepository extends \Doctrine\ORM\EntityRepository
{
/*	
	public function getGaleriasPlaya() {
		$q = $this->createQueryBuilder("g")
			->andWhere('g.id = :gal_1 OR g.id = :gal_2 OR g.id = :gal_3')
			->setParameter('gal_1', Galeria::GALERIA_EN_LA_PLAYA_CABANAS)
			->setParameter('gal_2', Galeria::GALERIA_EN_LA_PLAYA_LOFTS)
			->setParameter('gal_3', Galeria::GALERIA_EN_LA_PLAYA_COMUNES)
			;
		
		return $q->execute
	}*/
}
